name: Test WordPress Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: PHP ${{ matrix.php }} on WordPress ${{ matrix.wordpress }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        wordpress: ['5.9', '6.0', '6.1', '6.2', '6.3', '6.4']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml
        coverage: xdebug
        tools: composer:v2, phpunit

    - name: Install dependencies
      run: composer install

    - name: Setup WordPress test environment
      run: |
        bash bin/install-wp-tests.sh wordpress_test root '' localhost ${{ matrix.wordpress }}

    - name: Run tests
      run: composer test

    - name: Run PHP Code Sniffer
      run: composer lint

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 